### POST request to create a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "ameen",
  "email": "dohaqatar@gmail.com",
  "address": "Al izzath ",
  "dateOfBirth": "1984-01-01",
  "registeredDate": "2025-06-25"
}

###