### PUT request to update patient
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name" : "Al-Ameer Updated",
  "email": "ameersr@gmail.com",
  "address": "example address",
  "dateOfBirth": "1999-01-01"

}

###